name: test562

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6
      - name: Restore dependencies
        run: dotnet restore PowerThreadPool/PowerThreadPool.csproj
      - name: Build
        run: dotnet build PowerThreadPool/PowerThreadPool.csproj --no-restore
